name: Generate Changelog

on:
  push:
    branches:
      - feature/ci-cd
    paths-ignore:
      - CHANGELOG.md

jobs:
  build:
    name: changelog-generator
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate Change log
        run: |
          docker run -it --rm -v "$GITHUB_WORKSPACE":/usr/local/src/your-app githubchangeloggenerator/github-changelog-generator -u ${{ github.actor }} -p ${GITHUB_REPOSITORY#*/} -t ${{ github.token }}
      - name: push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "bot@github.actions"
          git remote set-url origin https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}
          git add CHANGELOG.md 
          git commit -m "chore: update CHANGELOG.md [skip ci]"
          git push

